Cart API View
egypt-shops/xshop-web pull request #133
Opened 2021-01-20 17:28 UTC by mmostafa74

Closes #88

2021-01-24 21:01 UTC, shahwan42 requested changes
xshop/cart/tests/test_cart.py shouldn't be empty. You must test the functionality of the Cart class!

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/serializers.py
> +        if quantity > 1 and not override_quantity:
Here

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/serializers.py
> +            serialized_product = ProductSerializer(product)
here

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/serializers.py
> +        attrs["product"] = serialized_product.data
Here
just `ProductSerializer(product).data` 3la tool

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +            400: "product_id Not found or Invalid quantity",
here

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +            400: "product_id Not found or Invalid quantity",
Try a list of errors

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +        return Response(cart)
here

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +            200: AddToCartSerializer,
Shouldn't this be a CartSerializer?

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +        return Response(cart, status=status.HTTP_200_OK)
I believe we can summarize those into one endpoint with GET, POST & PATCH Requests.
let's talk about it.

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/api/views.py
> +class RemoveFromCartApi(APIView):
Aren't these the same?

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/tests/test_api/test_serializers.py
> +        self.assertRaises(ValidationError, serializer.is_valid, raise_exception=True)
use assertRaisesMessage() to make sure the message we want is what's returned to the user

2021-01-24 21:01 UTC, shahwan42 commented on xshop/cart/tests/test_api/test_views.py
> +        # self.assertRaises(ValidationError, "product_id")
I believe this should be handled by ValidationErro, not 404, because it should be handled inside the Serializer, not the View. Let's discuss it.

2021-01-24 21:02 UTC, shahwan42 commented
Let's discuss those comments in a meeting tomorrow morning or evening

2021-01-25 20:04 UTC, mmostafa74 commented on xshop/cart/api/serializers.py
> +            serialized_product = ProductSerializer(product)
To be added:
- Change `AddToCartSerializer` to `CartSerializer`
- Adding Action field (Choice field) and validate which action to be done (Add, Update, Remove, Clear)
- No need for `quantity updated`

2021-01-25 20:04 UTC, mmostafa74 commented on xshop/cart/api/serializers.py
> +        if quantity > 1 and not override_quantity:
(Update Validation) if product exists in the cart -> check product.stock <= old quantity + incoming quantity

2021-01-25 20:05 UTC, mmostafa74 commented on xshop/cart/api/serializers.py
> +        attrs["product"] = serialized_product.data
`ProductSerializer(product).data` instead of `serialized_product.data`

2021-01-25 20:07 UTC, mmostafa74 commented on xshop/cart/api/urls.py
> +    path("", views.AddToCartApi.as_view(), name="add_get_clear_cart"),
One API view 
- `GET`: return cart details.
- `POST`: Cart Actions (add, update, remove, clear)

2021-01-25 20:09 UTC, mmostafa74 commented on xshop/cart/api/views.py
> +            400: "product_id Not found or Invalid quantity",
[product_id not found, invalid quantity] 
OR
[{"product_id": "Not Found"}, {"quantity": "invalid"}]

2021-01-25 20:11 UTC, mmostafa74 commented on xshop/cart/cart.py
> +from django.conf import settings
Add CartTests

2021-02-10 02:24 UTC, shahwan42 approved these changes

2021-02-10 02:24 UTC, shahwan42 commented on xshop/cart/api/serializers.py
> +    ("patch", "Update product in cart"),
'update' is better

2021-02-10 02:24 UTC, shahwan42 commented on xshop/cart/api/serializers.py
> +    actions = serializers.ChoiceField(choices=choices)
singular not plural: 'action' not 'action(s)'

2021-02-10 02:24 UTC, merged