user validation
egypt-shops/xshop-web pull request #138
Opened 2021-03-29 09:54 UTC by HMMK99

2021-03-29 15:30 UTC, mmostafa74 commented
run black to fix flake8 issues

2021-03-29 15:30 UTC, mmostafa74 commented
:rocket:

2021-03-29 21:52 UTC, shahwan42 requested changes

2021-03-29 21:52 UTC, shahwan42 commented on xshop/users/tests/test_models.py
> +        with self.assertRaises(ValidationError):
make sure the message is the same as the raised error's,
check here for more:
https://docs.djangoproject.com/en/3.1/topics/testing/tools/#assertions

2021-03-29 21:52 UTC, shahwan42 commented on xshop/users/tests/test_models.py
> +        with self.assertRaises(ValidationError):
here too

2021-03-29 21:52 UTC, shahwan42 commented on xshop/users/tests/test_models.py
> +        with self.assertRaises(ValidationError):
here too

2021-03-29 21:52 UTC, shahwan42 commented on xshop/users/tests/test_models.py
> +        with self.assertRaises(ValidationError):
here too

2021-03-30 10:53 UTC, shahwan42 approved these changes

2021-03-30 10:53 UTC, shahwan42 commented on xshop/users/mixins.py
> +class ShopRequiredMixin(object):
no need to specify `object` to inherit from

2021-03-30 10:53 UTC, merged