Export manager products
egypt-shops/xshop-web pull request #144
Opened 2021-03-31 15:02 UTC by HMMK99

2021-03-31 15:11 UTC, mmostafa74 commented on xshop/products/admin.py
> +            return Product.objects.filter(shop=Shop.objects.get(mobile=request.user.mobile))
try use Product.obejcts.filter(shop__in=request.user.shop)

2021-04-03 16:09 UTC, HMMK99 commented
Last update I used the mobile to select shop to make sure that the user is the manager of the shop.
as if I select any user connected to the shop then customers, DEC and Cashier can access the data.

2021-04-04 11:32 UTC, mmostafa74 requested changes

2021-04-04 11:32 UTC, mmostafa74 commented on xshop/products/tests/test_admin.py
> +from ...users.models import GeneralManager, User
Try from xshop.users.models import GeneralManager, User to be more readable

2021-04-05 01:57 UTC, shahwan42 requested changes

2021-04-05 01:57 UTC, shahwan42 commented on xshop/products/tests/test_admin.py
> +            list(Product.objects.filter(id=0).order_by("-id")),
why `id=0`? should you filter by the manager (manager1) of the shop that has no products?
`list(Product.objects.filter(shop=self.manager1.shop).order_by("-id"))`

2021-04-05 16:56 UTC, shahwan42 approved these changes

2021-04-05 17:04 UTC, mmostafa74 approved these changes

2021-04-05 17:04 UTC, merged