api for POST checkout
egypt-shops/xshop-web pull request #154
Opened 2021-04-09 06:04 UTC by HMMK99

2021-04-09 06:06 UTC, HMMK99 commented
still for 1 shop only

2021-04-11 12:05 UTC, mmostafa74 requested changes
Add serializers tests

2021-04-12 00:55 UTC, shahwan42 submitted a review, later dismissed

2021-04-12 00:55 UTC, shahwan42 commented
@mmostafa74 Please review it again and see if everything work as desired

2021-04-12 08:28 UTC, mmostafa74 requested changes

2021-04-12 08:28 UTC, mmostafa74 commented on xshop/orders/tests/test_api/test_serializers.py
> +            "object does not exist",
rename object to Shop

2021-04-12 08:28 UTC, mmostafa74 commented on xshop/orders/tests/test_api/test_serializers.py
> +            "object does not exist",
rename object to User

2021-04-17 03:25 UTC, shahwan42 requested changes

2021-04-17 03:25 UTC, shahwan42 commented on xshop/orders/api/urls.py
> +    path("checkout/", views.CheckoutApi.as_view(), name="checkout_operations"),
why not just `checkout` for the name?

2021-04-17 13:49 UTC, mmostafa74 approved these changes

2021-04-17 13:50 UTC, merged