create group with permissions
egypt-shops/xshop-web pull request #165
Opened 2021-04-26 04:34 UTC by ziadnabil

2021-04-26 20:07 UTC, mmostafa74 approved these changes

2021-04-26 20:07 UTC, mmostafa74 requested changes
Add tests

2021-04-28 12:19 UTC, shahwan42 commented
https://adamj.eu/tech/2020/09/07/how-to-unit-test-a-django-management-command/

2021-05-02 21:19 UTC, mmostafa74 commented
Can you please rename file to create_group

2021-05-03 06:41 UTC, shahwan42 commented on xshop/core/management/commands/create_groups.py
> +                    print("Creating {}".format(name))
use `self.stdout.write()` instead of print

2021-05-03 06:42 UTC, shahwan42 commented
@ziadnabil please try to finish this PR asap

2021-05-03 14:10 UTC, ziadnabil commented
> @ziadnabil please try to finish this PR asap

still fixing permission problem :
![Screenshot from 2021-05-03 16-07-13](https://user-images.githubusercontent.com/51180209/116886963-035d9280-ac2a-11eb-9fbd-60730ccda7f5.png)

2021-05-04 23:48 UTC, mmostafa74 requested changes

2021-05-04 23:48 UTC, mmostafa74 commented on xshop/core/management/commands/create_groups.py
> +class Command(BaseCommand):
remove permissions, you are supposed to create groups only

2021-05-05 18:25 UTC, mmostafa74 requested changes

2021-05-05 18:25 UTC, mmostafa74 commented on xshop/core/tests/test_views.py
> +        self.assertEqual(Group.objects.all().count(), 5)
make sure that desired groups created

2021-05-05 18:26 UTC, mmostafa74 commented on xshop/core/tests/test_views.py
> +        self.assertEqual(Group.objects.all().count(), 5)
self.assertTrue(Group.objects.get(name=UserGroup.CUSTOMER))

2021-05-05 19:07 UTC, mmostafa74 approved these changes, later dismissed

2021-05-09 20:23 UTC, merged