shop_and_product_details
egypt-shops/xshop-web pull request #168
Opened 2021-05-04 08:18 UTC by HMMK99

2021-05-04 08:20 UTC, HMMK99 commented
![Screenshot from 2021-05-04 10-18-47](https://user-images.githubusercontent.com/44302506/116977065-423f2700-acc2-11eb-9ff0-0066b3bbaa9b.png)
![Screenshot from 2021-05-04 10-18-53](https://user-images.githubusercontent.com/44302506/116977074-45d2ae00-acc2-11eb-90c5-db9174915a54.png)
![Screenshot from 2021-05-04 10-19-20](https://user-images.githubusercontent.com/44302506/116977077-4703db00-acc2-11eb-86de-7c813c9a88c8.png)

2021-05-04 22:48 UTC, mmostafa74 requested changes

2021-05-04 22:48 UTC, mmostafa74 commented on xshop/shops/views.py
> +    def post(self, request, *args, **kwargs):  # class based view def post, def get
why?

2021-05-04 22:48 UTC, mmostafa74 commented on xshop/shops/tests/test_views.py
> +class CartTests(TestCase):
Rename CartTests to ShopDetailViewTests

2021-05-04 22:48 UTC, mmostafa74 commented on xshop/shops/views.py
> +class ShopView(LoginRequiredMixin, ListView):
ShopDetailView

2021-05-04 22:48 UTC, mmostafa74 commented on xshop/products/tests/test_views.py
> +class CartTests(TestCase):
change CartTests

2021-05-04 23:52 UTC, mmostafa74 requested changes

2021-05-04 23:52 UTC, mmostafa74 commented on xshop/products/tests/test_views.py
> +    def test_get_product_details(self):
assert template used, and content

2021-05-04 23:52 UTC, mmostafa74 commented on xshop/shops/tests/test_views.py
> +    def test_get_shop_details(self):
same

2021-05-05 22:00 UTC, mmostafa74 approved these changes

2021-05-09 22:38 UTC, merged