firstTryinvoicing
egypt-shops/xshop-web pull request #77
Opened 2020-10-21 16:17 UTC by HMMK99

2020-10-21 17:00 UTC, shahwan42 requested changes

2020-10-21 17:00 UTC, shahwan42 commented on xshop/invoices/urls.py
> +app_name = "core"
app_name = "invoices"

2020-10-21 18:42 UTC, HMMK99 commented
![VirtualBox_Tomy_21_10_2020_20_22_13](https://user-images.githubusercontent.com/44302506/96768092-b62c7880-13dd-11eb-9a1e-af4dcf18143d.png)

this is the most visible version I got

2020-10-21 20:29 UTC, shahwan42 requested changes
أحسن كتير
لو تلاحظ، في الكتاب حاول يخلي الاستايلز زي الاستايل بتاع جانجو أدمن الأساسي..
بس احنا هنا بنستخدم أدمن تمبلت مختلف، اسمه django-jazzmin
حاول تخلي الاستايل شبهه
أو استخدم كومبوننت منه، زي table يعني موجود وخلاص

https://github.com/farridav/django-jazzmin

https://stackoverflow.com/questions/6583877/how-to-override-and-extend-basic-django-admin-templates

2020-10-21 20:36 UTC, shahwan42 commented
and please use sensible commit messages instead of these 
![image](https://user-images.githubusercontent.com/6496157/96783460-ce0bf880-13ed-11eb-94e7-564913b9955d.png)

2020-10-22 07:07 UTC, HMMK99 commented
![VirtualBox_Tomy_22_10_2020_09_04_54](https://user-images.githubusercontent.com/44302506/96836955-fa536380-1445-11eb-9d94-afae615c86b2.png)

2020-10-22 07:34 UTC, shahwan42 approved these changes

2020-10-22 07:35 UTC, merged