manager user mixins full CRUD, read&update, and read
egypt-shops/xshop-web pull request #93
Opened 2020-11-05 07:31 UTC by HMMK99

without the Mixin
![VirtualBox_Tomy_05_11_2020_09_21_20](https://user-images.githubusercontent.com/44302506/98210476-5095cb80-1f49-11eb-805c-53143baeaba8.png)
with the Mixin
![VirtualBox_Tomy_05_11_2020_09_20_10](https://user-images.githubusercontent.com/44302506/98210505-5a1f3380-1f49-11eb-88ec-d6e2e2fe14c0.png)

2020-11-05 08:35 UTC, shahwan42 requested changes

2020-11-05 08:35 UTC, shahwan42 commented on xshop/users/mixins.py
> +            and len(Shop.objects.filter(mobile=request.user.mobile)) > 0
`Shop.objects.filter(mobile=request.user.mobile).exists()` would be better

2020-11-05 08:37 UTC, shahwan42 commented
add extra validation in the User model to make sure that if the new user is `User.Types.Manager` must be  connected to a shop,

HELP
https://stackoverflow.com/questions/7366363/adding-custom-django-model-validation

2020-11-10 06:45 UTC, shahwan42 requested changes
could you please test it?

inside test_models in users.tests package
create a new ManagerTests class,
and test creating a manager without a shop raises a validation error inside a method

2020-11-10 06:47 UTC, shahwan42 commented
also, fix the failing tests in the CI

2020-11-10 06:58 UTC, HMMK99 commented
> could you please test it?
> 
> inside test_models in users.tests package
> create a new ManagerTests class,
> and test creating a manager without a shop raises a validation error inside a method

 I was working on it but the validation error keeps rising without testing

2020-11-10 06:59 UTC, shahwan42 commented
You need to edit code and add a shop to manager users inside the tests to satisfy the new requirement (shop connected to manager)

2020-11-10 07:26 UTC, HMMK99 commented
created with shop
![VirtualBox_Tomy_10_11_2020_08_09_04](https://user-images.githubusercontent.com/44302506/98642759-a21dcc00-2336-11eb-8654-a7efd1b47545.png)
validation error without shop
![VirtualBox_Tomy_10_11_2020_08_10_34](https://user-images.githubusercontent.com/44302506/98642762-a34ef900-2336-11eb-8ecb-898d4e7220bf.png)

2020-11-10 23:49 UTC, shahwan42 approved these changes

2020-11-10 23:49 UTC, merged